### ISSUE TITLE
Removing !important tags

### ISSUE THREAD

**Issue by Ethanhackett** [jgallen23/grunt-inline-css#24]
It appears that during the inline process all of the !important tags are getting stripped out of inline.

**Comment by mzgajner** [comment]
Yup, Juice does this, and it's bad, because this is important for some older email clients.

But the good news is they added an option for this (`preserveImportant: true`) in version 1.3.0. So basically, you just have to bump the juice version in `package.json` to the latest one and specify the aforementioned option.

**Comment by blacksun1** [comment]
HI,

Juice has been upgraded to 3.0.1 in master and I've added tests to check that !important is not being stripped when using the Juice `preserveImportant: true` option.


Regards,
